services:
  api:
    container_name: api-prod
    build:
      context: ..
      dockerfile: ./apps/api/prod.Dockerfile
    env_file:
      - ./docker/.env.prod
    ports:
      - "3000:3000"
    restart: unless-stopped
